"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { Camera, LoaderCircle, Save } from "lucide-react";

type Profile = {
  careName?: string; profilePicture?: string; phoneNumber?: string; email?: string;
  dateOfBirth?: string; gender?: "male" | "female"; address?: string; country?: string;
  region?: string; nationality?: string; postCode?: string;
  emergencyContactName?: string; emergencyContactRelationship?: string; emergencyContactPhoneNumber?: string;
};
type Form = Required<Omit<Profile, "profilePicture" | "gender">> & { gender: "" | "male" | "female" };
const blank: Form = { careName: "", phoneNumber: "", email: "", dateOfBirth: "", gender: "", address: "", country: "", region: "", nationality: "", postCode: "", emergencyContactName: "", emergencyContactRelationship: "", emergencyContactPhoneNumber: "" };
const imageFallback = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80";
const options = { country: ["United Kingdom", "England", "Scotland", "Wales"], region: ["London", "Manchester", "Birmingham", "Leeds"], nationality: ["British", "Irish", "Scottish", "Welsh"], emergencyContactRelationship: ["Parent", "Sibling", "Spouse", "Friend"] };

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) {
  return <label className="flex flex-col gap-2"><span className="font-medium text-slate-800">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="h-12 rounded-lg border border-neutral-400 bg-transparent px-4 text-slate-700 outline-none focus:border-cyan-700" /></label>;
}
function Select({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: string[] }) {
  return <label className="flex flex-col gap-2"><span className="font-medium text-slate-800">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="h-12 rounded-lg border border-neutral-400 bg-transparent px-4 text-slate-700 outline-none focus:border-cyan-700"><option value="">Choose any one</option>{items.map((item) => <option key={item}>{item}</option>)}</select></label>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl bg-[#eef6ff] p-6"><h2 className="text-xl font-semibold text-slate-800">{title}</h2><div className="mt-5 flex flex-col gap-5">{children}</div></section>; }

export function CarerProfilePage() {
  const [form, setForm] = useState<Form>(blank); const [photo, setPhoto] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploadingPhoto, setUploadingPhoto] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const photoInput = useRef<HTMLInputElement>(null);
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm((current) => ({ ...current, [key]: value }));
  useEffect(() => { (async () => { try { const response = await fetch("/api/care/profile", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body?.message || "Unable to load your profile"); const profile: Profile = body.data ?? body; setPhoto(profile.profilePicture ?? ""); setForm({ ...blank, ...profile, dateOfBirth: profile.dateOfBirth?.slice(0, 10) ?? "", gender: profile.gender ?? "" }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load your profile"); } finally { setLoading(false); } })(); }, []);
  async function selectPhoto(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { setError("Please select an image file"); return; } if (file.size > 5 * 1024 * 1024) { setError("Profile photo must be 5 MB or smaller"); return; } setUploadingPhoto(true); setError(""); setNotice(""); const previewUrl = URL.createObjectURL(file); setPhoto(previewUrl); try { const payload = new FormData(); payload.append("profilePicture", file); const response = await fetch("/api/care/profile", { method: "PATCH", body: payload }); const body = await response.json(); if (!response.ok) throw new Error(body?.message || "Unable to upload profile photo"); setPhoto((body.data ?? body).profilePicture ?? previewUrl); setNotice("Profile photo updated successfully"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to upload profile photo"); } finally { setUploadingPhoto(false); event.target.value = ""; } }
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); setNotice(""); try { const payload = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value) payload.append(key, value); }); const response = await fetch("/api/care/profile", { method: "PATCH", body: payload }); const body = await response.json(); if (!response.ok) throw new Error(body?.message || "Unable to update your profile"); setPhoto((body.data ?? body).profilePicture ?? photo); setNotice(body.message || "Profile updated successfully"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update your profile"); } finally { setSaving(false); } }
  const name = form.careName.trim().split(/\s+/); const first = name[0] ?? ""; const last = name.slice(1).join(" ");
  if (loading) return <div role="status" className="p-10 text-center text-slate-600">Loading profile…</div>;
  return <form onSubmit={submit} className="min-h-screen bg-white px-6 py-6 sm:px-8 xl:px-10">
    {(error || notice) && <p role={error ? "alert" : "status"} className={`mb-4 rounded-lg px-4 py-3 ${error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{error || notice}</p>}
    <div className="grid gap-4 xl:grid-cols-[460px_minmax(0,1fr)]"><div className="space-y-4"><section className="overflow-hidden rounded-2xl bg-[#eef6ff]"><div className="h-40 bg-slate-300" /><div className="relative px-6 pb-6 pt-14"><input ref={photoInput} type="file" accept="image/*" className="sr-only" onChange={selectPhoto} /><div className="absolute left-6 top-0 -translate-y-1/2"><img src={photo || imageFallback} alt="Your profile" className="h-28 w-28 rounded-full border-4 border-[#eef6ff] object-cover" /><button type="button" onClick={() => photoInput.current?.click()} disabled={saving || uploadingPhoto} aria-label="Choose profile photo" className="absolute bottom-0 right-0 inline-flex h-9 w-9 items-center justify-center rounded-full bg-cyan-700 text-white shadow transition hover:bg-cyan-800 disabled:opacity-60">{uploadingPhoto ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Camera className="h-4 w-4" />}</button></div><div className="pl-32"><h1 className="text-3xl font-semibold text-black">{form.careName || "Your name"}</h1><p className="text-slate-500">{form.email || "Your email"}</p><button type="button" onClick={() => photoInput.current?.click()} disabled={uploadingPhoto} className="mt-2 text-sm font-medium text-cyan-700 hover:text-cyan-800 disabled:opacity-60">{uploadingPhoto ? "Uploading photo…" : "Change photo"}</button></div></div></section><Card title="Personal Information"><Field label="First Name" value={first} onChange={(value) => set("careName", `${value} ${last}`.trim())} /><Field label="Last Name" value={last} onChange={(value) => set("careName", `${first} ${value}`.trim())} /><div className="grid gap-5 md:grid-cols-2"><Field label="Date of Birth" type="date" value={form.dateOfBirth} onChange={(value) => set("dateOfBirth", value)} /><fieldset><legend className="font-medium text-slate-800">Gender</legend><div className="mt-3 flex gap-5">{(["male", "female"] as const).map((gender) => <label key={gender} className="capitalize"><input type="radio" name="gender" checked={form.gender === gender} onChange={() => set("gender", gender)} /> {gender}</label>)}</div></fieldset></div></Card></div>
      <div className="space-y-4"><Card title="Contact Information"><div className="grid gap-5 md:grid-cols-2"><Field label="Email" type="email" value={form.email} onChange={(value) => set("email", value)} /><Field label="Phone Number" value={form.phoneNumber} onChange={(value) => set("phoneNumber", value)} /></div><div className="grid gap-5 md:grid-cols-2"><Select label="Country" value={form.country} onChange={(value) => set("country", value)} items={options.country} /><Select label="State/Region" value={form.region} onChange={(value) => set("region", value)} items={options.region} /></div><div className="grid gap-5 md:grid-cols-2"><Select label="Nationality" value={form.nationality} onChange={(value) => set("nationality", value)} items={options.nationality} /><Field label="Postcode" value={form.postCode} onChange={(value) => set("postCode", value)} /></div><label className="flex flex-col gap-2"><span className="font-medium text-slate-800">Address</span><textarea value={form.address} onChange={(e) => set("address", e.target.value)} rows={4} className="rounded-lg border border-neutral-400 bg-transparent p-4 text-slate-700 outline-none focus:border-cyan-700" /></label></Card><Card title="Emergency Contact"><Field label="Contact Name" value={form.emergencyContactName} onChange={(value) => set("emergencyContactName", value)} /><div className="grid gap-5 md:grid-cols-2"><Select label="Relationship" value={form.emergencyContactRelationship} onChange={(value) => set("emergencyContactRelationship", value)} items={options.emergencyContactRelationship} /><Field label="Phone Number" value={form.emergencyContactPhoneNumber} onChange={(value) => set("emergencyContactPhoneNumber", value)} /></div></Card></div></div>
    <div className="mt-6 flex justify-end"><button disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-lg bg-indigo-700 px-5 font-semibold text-white hover:bg-indigo-800 disabled:opacity-60"><Save className="h-4 w-4" />{saving ? "Saving…" : "Save changes"}</button></div>
  </form>;
}
